export const ICONS = {
  IDicons: require('./IDicons/IDicons.i.png'),
  SearchIcons: require('./SearchIcons/SearchIcon.i.png'),
  NotificationIcons: require('./NotificationIcons/BellImg.i.png'),
  Letsicons: require('./LetsIcons/LetsIcon.i.png'),
  eye: require('./eye/eye.i.png'),
  eyeoff: require('./eyeoff/eyeoff.i.png'),
  error: require('./error/Vector.png'),
  backarrow: require('./backarrow/ion_arrow-back-outline.png'),
  edit: require('./edit/Group.png'),
  cam: require('./camera/Group.png'),
  lang: require('./lang/Lang.i.png'),
  right: require('./rightarrow/Vector.png'),
  privacy: require('./privacy/Privacy.i.png'),
  bell: require('./bell/basil_notification-on-outline.png'),
  theme: require('./theme/Vector.png'),
  help: require('./help/Help.i.png'),
  logout: require('./logout/Logout.i.png'),
  // chatbot: require('../../images/icon/ChatBot/ChatBot.i.png'),
  SendIcon: require('./SendIcons/SendIcon.i.png'),
  Location: require('../icon/BillIcons/location.png'),
  Mail: require('../icon/BillIcons/mail.png'),
  Phone: require('../icon/BillIcons/phone-call.png'),
  Popup:require('../icon/PopUp/PopUp.i.png'),
  Alert:require('./Alert/Alert.i.png'),
};
