export const ICONS = {
  IDicons: require('./IDicons/IDicons.i.png'),
  SearchIcons: require('./SearchIcons/SearchIcon.i.png'),
  NotificationIcons: require('./NotificationIcons/Notification.i.png'),
  Letsicons: require('./LetsIcons/LetsIcon.i.png'),
  eye: require('./eye/eye.png'),
  eyeoff: require('./eyeoff/hidden.png'),
  error: require('./error/Vector.png'),
  backarrow: require('./backarrow/ion_arrow-back-outline.png'),
  edit: require('./edit/Group.png'),
  cam: require('./camera/Group.png'),
  lang: require('./lang/Group.png'),
  right: require('./rightarrow/Vector.png'),
  privacy: require('./privacy/material-symbols_privacy-tip-outline.png'),
  bell: require('./bell/basil_notification-on-outline.png'),
  theme: require('./theme/Vector.png'),
  help: require('./help/material-symbols_help-outline.png'),
  logout: require('./logout/ant-design_logout-outlined.png'),
  // chatbot: require('../../images/icon/ChatBot/ChatBot.i.png'),
  SendIcon: require('./SendIcons/SendIcon.i.png'),
  Location: require('../icon/BillIcons/location.png'),
  Mail: require('../icon/BillIcons/mail.png'),
  Phone: require('../icon/BillIcons/phone-call.png'),
};
