export const IMAGE: any = {
    Walkthrough1Img: require('./Walkthrough1Images/Walkthrough1.i.png'),
    Walkthrough2Img: require('./Walkthrough2Images/Walkthrough2.i.png'),
    Walkthrough3Img: require('./Walkthrough3Images/Walkthrough3.i.png'),
    LoginLogoImg: require('./LoginLogoImages/LoginLogo.i.png'),
    ForgotPasswordMobImg: require('./ForgotPasswordMobImages/ForgotPasswordMobImg.i.png'),
    OTPverification:require('./OTPVerificationImages/otpverifyImg.i.png'),
    CreateNewPasswordImg:require('./CreateNewPasswordImages/CreateNewPass.i.png'),
    ModalImg:require('./ModalImages/ModalSuccess.i.png'),
    BigDropImg:require('./BigDropImages/BigDrop.i.png'),
    SmallDropImg:require('./SmallDropImages/SmallDrop.i.png'),
    DashboardImg:require('./DashboardImages/DashboardImg.i.png'),
    BigDropDash:require('./BigDropDashImages/BigDropDash.i.png'),
    HomeDashImg:require('./HomeDashImages/HomeDash.i.png'),
    HomeTempDashImg:require('./HomeTempDashImages/DashTempHome.i.png'),
    ProfileAvatarImg: require('./ProfileAvatarImages/ProfileAvatar.i.png'),
    Splash1LogoImg: require('./Splash1Images/Splash1Logo.i.png'),
    Splash2LogoImg: require('./Splash2Images/Splash2Logo.i.png'),
    BotLogoSplashImg: require('./BotLogoSplashImages/BotLogoSplash.i.png'),
};
